version: '3'
services:
  website:
    restart: unless-stopped
    image: sadema/genericwebsite
    container_name: genericwebsite
    ports:
      - "80:80"

  database:
    restart: unless-stopped
    image: sadema/couchdb
    container_name: website-testdatabase
    ports:
      - "6910:5984"
    volumes:
      - website-testdata:/usr/local/var/lib/couchdb

volumes:
  website-testdata:
